name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shreytan  # Change this to your GitHub username
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_repositories: yes
          plugin_repositories_featured: Shreytan/Cohort-2.0
          plugin_stars: yes
